/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   '#9392ff',
        'primary-dim':               '#6462ec',
        'primary-fixed':             '#bbbbff',
        'primary-fixed-dim':         '#acabff',
        'primary-container':         '#7472fd',
        'on-primary':                '#0e0078',
        'on-primary-fixed':          '#13008e',
        'on-primary-fixed-variant':  '#322bbb',
        'on-primary-container':      '#000000',
        'inverse-primary':           '#4e4bd5',
        'secondary':                 '#c0caac',
        'secondary-dim':             '#b3bd9f',
        'secondary-fixed':           '#ebf5d4',
        'secondary-fixed-dim':       '#dce7c7',
        'secondary-container':       '#202814',
        'on-secondary':              '#3a432c',
        'on-secondary-fixed':        '#424b34',
        'on-secondary-fixed-variant':'#5e684e',
        'on-secondary-container':    '#9ea88b',
        'tertiary':                  '#e1ff9d',
        'tertiary-dim':              '#c3e379',
        'tertiary-fixed':            '#d1f286',
        'tertiary-fixed-dim':        '#c3e379',
        'tertiary-container':        '#d1f286',
        'on-tertiary':               '#4a6402',
        'on-tertiary-fixed':         '#344700',
        'on-tertiary-fixed-variant': '#4c6604',
        'on-tertiary-container':     '#435b00',
        'surface':                   '#060e20',
        'surface-dim':               '#060e20',
        'surface-bright':            '#172b54',
        'surface-variant':           '#142449',
        'surface-tint':              '#9392ff',
        'surface-container-lowest':  '#000000',
        'surface-container-low':     '#081329',
        'surface-container':         '#0c1934',
        'surface-container-high':    '#101e3e',
        'surface-container-highest': '#142449',
        'on-surface':                '#dee5ff',
        'on-surface-variant':        '#9baad6',
        'inverse-surface':           '#faf8ff',
        'inverse-on-surface':        '#4d556b',
        'background':                '#060e20',
        'on-background':             '#dee5ff',
        'outline':                   '#65759e',
        'outline-variant':           '#38476d',
        'error':                     '#fd6f85',
        'error-dim':                 '#c8475d',
        'error-container':           '#8a1632',
        'on-error':                  '#490013',
        'on-error-container':        '#ff97a3',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.25rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      boxShadow: {
        'ambient':   '0px 10px 40px rgba(0, 0, 12, 0.4)',
        'primary':   '0px 8px 32px rgba(147, 146, 255, 0.20)',
        'card':      '0px 4px 24px rgba(0, 0, 20, 0.3)',
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(135deg, #9392ff 0%, #6462ec 100%)',
      },
      keyframes: {
        'fade-in': {
          '0%':   { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.2' },
          '50%':      { opacity: '0.4' },
        },
        'spin-slow': {
          '0%':   { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'fade-in':   'fade-in 0.4s ease-out',
        'slide-up':  'slide-up 0.5s ease-out',
        'pulse-glow':'pulse-glow 3s ease-in-out infinite',
        'spin-slow': 'spin-slow 3s linear infinite',
      },
    },
  },
  plugins: [],
}
